apiVersion: v1
kind: Pod
metadata:
  name: study
spec:
  containers:
  - name: study
    image: nginx:latest
    volumeMounts:
    - name: vol1
      mountPath: "/tmp/data"
  volumes:
  - name: vol1
    persistentVolumeClaim:
      claimName: auto-ebs-claim
